version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Australia/Brisbane
  open-pull-requests-limit: 3
  reviewers:
  - matanui159
